# Use root/root as user/password credentials

## In Container customisation
# When a container is started for the first time, a new database with the specified name will be
# created and initialized with the provided configuration variables.
# Furthermore, it will execute files with extensions .sh, .sql, .sql.gz, and .sql.xz that are
# found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order.
# .sh files without file execute permission are sourced rather than executed.
# You can easily populate your mariadb services by mounting a SQL dump into that directory
# and provide custom images with contributed data. SQL files will be imported by default to the database
# specified by the MARIADB_DATABASE / MYSQL_DATABASE variable.
version: "3.1"

services:
  web:
    build: .
    image: clowa/visitors
    restart: always
    ports:
      - 80:8080
    environment:
      VISITS_PORT: 8080
      VISITS_REDIS_HOST: redis:6379
      VISITS_REDIS_DB: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s

  redis:
    image: redis:6-alpine
    restart: always
