name: Build docker images
on:
  pull_request:

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo ::set-output name=version::$(cat VERSION)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Test docker build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: false
          platforms: |
            linux/386
            linux/s390x
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
            linux/mips64le
          build-args: |
            GO_VERSION=1.19.5
            ALPINE_VERSION=3.16
            APP_VERSION=${{ steps.version.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:buildcache
